name: ${project.name}
version: ${project.version}
description: Allows you to set custom message for when a use leaves/joins or gets kicked.
author: unlucky4ever
website: ${project.url}

main: com.unlucky4ever.customjoinmessage.CustomJoinMessage

commands:
  cjm:
    description: Basic commands for CustomJoinMessage
    usage: |
           /<command> - Basic commands for CustomJoinMessage

permissions:
  cjm.admin:
    description: Notifies the player when CustomJoinMessage is in need of an update.
    default: op
  cjm.reload:
    description: Allows the player to reload the config.yml
    default: op